name: Test Default Working Dir

on:
  workflow_dispatch:

jobs:
  clone_default_v1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'

      - name: Clone (Default)
        uses: actions/checkout@v1

      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'

  clone_other_path_v1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'

      - name: Clone (other_path)
        uses: actions/checkout@v1
        with:
          path: repo-local/test_action_repo

      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'


  clone_default_v2:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'

      - name: Clone (Default)
        uses: actions/checkout@v2

      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'

  clone_other_path_v2:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'

      - name: Clone (other_path)
        uses: actions/checkout@v2
        with:
          path: repo-local/test_action_repo

      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'


  clone_default_v3:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'

      - name: Clone (Default)
        uses: actions/checkout@v3

      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'

  clone_other_path_v3:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'

      - name: Clone (other_path)
        uses: actions/checkout@v3
        with:
          path: repo-local/test_action_repo

      - name: Print directory
        run: |
          echo -e "GITHUB_WORKSPACE \n${GITHUB_WORKSPACE}\n"
          echo -e "github.workspace:\n${{ github.workspace }}\n"
          echo -e "pwd:\n $(pwd)\n"
          echo "ls"
          ls -als
          echo "find"
          find /home/runner/work/test_action -name '.git'


